version: "3"

services: 
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes: 
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_HOST=app
      - DB_HOST=postgres
      - DB_HOST=supersecretpassword
    depends_on: 
      - db

  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=supersecretpassword